{% set name = "loguru" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e0e6ff59be5e22f863d909ca989e34bb14c21b374f6af45281e603d003dbb96

build:
  number: 1
  skip: true  # [py2k]
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - colorama >=0.3.4        # [win]
    - win32_setctime >=1.0.0  # [win]
    - aiocontextvars          # [py36]

test:
  imports:
    - loguru

about:
  home: https://github.com/Delgan/loguru
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python logging made (stupidly) simple
  dev_url: https://github.com/Delgan/loguru

extra:
  recipe-maintainers:
    - mariusvniekerk
