{% set name = "loguru" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 066bd06758d0a513e9836fd9c6b5a75bfb3fd36841f4b996bc60b547a309d41c

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - colorama >=0.3.4        # [win]
    - win32_setctime >=1.0.0  # [win]

test:
  imports:
    - loguru

about:
  home: https://github.com/Delgan/loguru
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python logging made (stupidly) simple
  dev_url: https://github.com/Delgan/loguru

extra:
  recipe-maintainers:
    - davidbrochart
    - mariusvniekerk
