{% set name = "loguru" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02967ccdfcd5999fe2ffc03eb93a4da8b55b8308547dec6273caf349baeff592

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - ansimarkup >=1.4.0
    - better_exceptions_fork >=0.2.1.post6
    - colorama >=0.3.4
    - python >=3.5

test:
  imports:
    - loguru

about:
  home: https://github.com/Delgan/loguru
  license: MIT
  license_family: MIT
  # Package does not ship its license presently
  # license_file: LICENSE
  summary: Python logging made (stupidly) simple
  dev_url: https://github.com/Delgan/loguru

extra:
  recipe-maintainers:
    - mariusvniekerk
